#!/bin/bash
# Example setup script for Wit.ai audio processing

echo "========================================"
echo "Wit.ai Audio Processing Setup Example"
echo "========================================"

echo ""
echo "1. Get your Wit.ai API key:"
echo "   - Go to https://wit.ai"
echo "   - Create an account or log in"
echo "   - Create a new app"
echo "   - Go to Settings → API Details"
echo "   - Copy your Server Access Token"
echo ""

echo "2. Set environment variable:"
echo "   export WIT_API_KEY_DEFAULT='YOUR_WIT_AI_SERVER_ACCESS_TOKEN'"
echo ""

echo "3. Optional: Set language-specific keys:"
echo "   export WIT_API_KEY_ENGLISH='english_app_token'"
echo "   export WIT_API_KEY_ARABIC='arabic_app_token'"
echo "   export WIT_API_KEY_FRENCH='french_app_token'"
echo ""

echo "4. Start the Wit.ai audio processing system:"
echo "   bash /root/clawd/scripts/start_wit_audio_processing.sh"
echo ""

echo "5. Test the system:"
echo "   python3 /root/clawd/scripts/whatsapp_simulator.py --wit"
echo ""

echo "6. Monitor logs:"
echo "   tail -f /root/clawd/audio/wit.log"
echo ""

echo "7. Stop the system:"
echo "   bash /root/clawd/scripts/stop_audio_processing.sh"
echo ""

echo "========================================"
echo "File Structure:"
echo "========================================"
echo "/root/clawd/audio/"
echo "├── incoming/      # New audio files appear here"
echo "├── processed/     # Processed audio files moved here"
echo "├── transcripts/   # Transcripts and metadata saved here"
echo "└── wit.log       # Log file"
echo ""
echo "/root/clawd/sessions/"
echo "└── *.txt         # Session files for Clawdbot to read"
echo ""

echo "========================================"
echo "Testing with Real Audio:"
echo "========================================"
echo "1. Place an audio file in the incoming directory:"
echo "   cp /path/to/your/audio.ogg /root/clawd/audio/incoming/212626474248_$(date +%s).ogg"
echo ""
echo "2. The system will automatically:"
echo "   - Detect the new file"
echo "   - Convert to WAV format"
echo "   - Send to Wit.ai for transcription"
echo "   - Save transcript to /root/clawd/audio/transcripts/"
echo "   - Create session file for Clawdbot"
echo ""

echo "========================================"
echo "Troubleshooting:"
echo "========================================"
echo "1. Check if services are running:"
echo "   ps aux | grep -E '(wit_audio_handler|clawdbot_integration)'"
echo ""
echo "2. Check logs:"
echo "   tail -f /root/clawd/audio/wit.log"
echo ""
echo "3. Test Wit.ai API directly:"
echo "   curl -X POST 'https://api.wit.ai/speech' \\"
echo "     -H 'Authorization: Bearer YOUR_API_KEY' \\"
echo "     -H 'Content-Type: audio/wav' \\"
echo "     --data-binary @/path/to/audio.wav"
echo ""

echo "Done!"